Description: Cria bucket no S3 #comentário

Resources:

  BucketTonyS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucket-do-tony-bootcamp-ed
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
             SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True